Intake
frc937/robot2024 pull request #17
Opened 2024-01-23 22:41 UTC by Berdenson

You can press the A button to run the intake. (intake motor speed may need to be flipped, but that's for later)

2024-01-23 22:51 UTC, QuackitsQuinn submitted a review, later dismissed
looks good, thank you for documenting everything.

2024-01-24 22:19 UTC, willitcode requested changes
See individual code comments.

2024-01-24 22:19 UTC, willitcode commented on src/main/java/frc/robot/Constants.java
> +
Will want a DIO port ID for the limit switch here somewhere.

2024-01-24 22:19 UTC, willitcode commented on src/main/java/frc/robot/subsystems/Intake.java
> +  private Spark intake;
Needs to be a CANSparkMax in Brushless mode

2024-01-24 22:19 UTC, willitcode commented on src/main/java/frc/robot/subsystems/Intake.java
Add a method somewhere in this class to get the state of the limit switch

2024-01-24 22:19 UTC, willitcode commented on src/main/java/frc/robot/commands/RunIntake.java
> +    return false;
We have two options here. Either return the state of the limit switch from this method, or (better yet) we create this command and a command that ends when the limit switch is `true`, and put them in a ParallelRaceGroup. You need to try the ParallelRaceGroup method first and see if it causes an error where the commands conflict with each other—simulation mode is your bestie (or maybe you can talk electrical into plugging a Spark Max and a limit switch into the test board for you, idk).

2024-01-24 23:38 UTC, willitcode commented on src/main/java/frc/robot/commands/RunIntake.java
> +    return false;
Okay, decision has been made: do the first option. Just return the state of the limit switch from the `isFinished()` method of `RunIntake`.

2024-01-25 01:00 UTC, willitcode requested changes
Looks good! Thanks!

2024-01-25 01:03 UTC, willitcode requested changes
Sorry...

2024-01-25 01:03 UTC, willitcode commented on src/main/java/frc/robot/commands/RunIntake.java
> +    this.intake = RobotContainer.intake;
call `addRequirements(Command...)`

2024-01-25 01:15 UTC, willitcode approved these changes
Looks good! Thanks! Sorry about all the change-request chaos.

2024-01-25 01:16 UTC, merged