Update Pneumatics Code to Use Spikes
frc937/robot2024 pull request #178
Opened 2024-04-03 15:41 UTC by quackitsquinn

Updates the code for pneumatics to use Spike relays instead of a PCM.

2024-04-03 15:48 UTC, willitcode commented
Tag the issue number

2024-04-03 16:38 UTC, willitcode requested changes
Looks good except for one minor comment. @Berdenson please review for any JavaDoc nonsense that I missed

2024-04-03 18:51 UTC, Berdenson requested changes
javadocccccc

2024-04-03 18:51 UTC, Berdenson commented on src/main/java/frc/robot/RobotContainer.java
> +  public static Compressor compressor = new Compressor();
this needs javadoc

2024-04-03 18:51 UTC, Berdenson commented on src/main/java/frc/robot/RobotContainer.java
> +  public static ControlCompressor controlCompressor = new ControlCompressor();
this also needs javadoc

2024-04-03 19:06 UTC, Berdenson approved these changes
yea looks good

2024-04-04 04:20 UTC, willitcode approved these changes

2024-04-04 11:24 UTC, merged