Gkc javadoc v2
frc937/robot2024 pull request #188
Opened 2024-04-22 21:42 UTC by Berdenson

Closes #180 
Implements javadoc for all the gkc things

2024-04-22 21:46 UTC, quackitsquinn requested changes
have fun :)

2024-04-22 21:46 UTC, quackitsquinn commented on src/main/java/frc/robot/commands/auto/OnePieceAutoButItWorksISwear.java
> +/** Auto that drives to the amp and offloads the note. */
Add reasoning why this exists (non-functional limelight at comp)

2024-04-29 20:18 UTC, willitcode requested changes
Please do the bare minimum and run spotless so that your code builds before requesting my review.

2024-04-29 20:24 UTC, quackitsquinn approved these changes

2024-04-29 20:28 UTC, willitcode approved these changes
eh probably good enough, I trust you to be more nitpicky about javadoc than me

2024-04-29 20:30 UTC, merged