Implement Limelight
frc937/robot2024 pull request #43
Opened 2024-02-03 15:51 UTC by MarissaKoglesby

closes #25

2024-02-03 16:23 UTC, willitcode requested changes
have fun

2024-02-03 16:23 UTC, willitcode commented on src/main/java/frc/robot/commands/AimWithLimelight.java
> +  /** Creates a new AimWithLimelight. */
Also make sure there's more than just `@param`s but the `@param`s are the most important part

2024-02-03 18:11 UTC, willitcode requested changes
Go through all JavaDoc and capitalize Limelight anywhere it isn't capitalized

2024-02-03 18:11 UTC, willitcode commented on src/main/java/frc/robot/Constants.java
> +      /**
Fix this JavaDoc to actually describe what the var is. Also you can't have multiple JavaDoc comments on one field I don't think

2024-02-03 18:11 UTC, willitcode commented on src/main/java/frc/robot/RobotContainer.java
> +  public static Limelight limelight = new Limelight("limelight");
JavaDoc

2024-02-03 18:11 UTC, willitcode commented on src/main/java/frc/robot/commands/AimWithLimelight.java
> +  /**
Finish the JavaDoc

2024-02-03 18:11 UTC, willitcode commented on src/main/java/frc/robot/commands/AimWithLimelight.java
> +   * @param limelight The limelight to aim with.
The Limelight subsystem to aim with

2024-02-03 18:11 UTC, willitcode commented on src/main/java/frc/robot/commands/AimWithLimelight.java
> +   * @param mountAngle The number of degrees the limelight is mounted back from perfectly vertical.
Does positive mean it's mounted pointing down from perfectly vertical or pointing up from perfectly vertical?

2024-02-03 18:11 UTC, willitcode commented on src/main/java/frc/robot/commands/AimWithLimelight.java
> +   * @param driveStrength How hard to drive towards the target.
Clarify the range in this value

2024-02-03 18:11 UTC, willitcode commented on src/main/java/frc/robot/commands/AimWithLimelight.java
> +   * @param speedLimit Basic speed limit to make sure we don't drive too fast.
Explain how to use this

2024-02-03 18:11 UTC, willitcode commented on src/main/java/frc/robot/commands/AimWithLimelight.java
> +   * @param turnDoneThreshold The threshold in angles when we consider the aiming done.
Degrees or Radians?

2024-02-03 18:11 UTC, willitcode commented on src/main/java/frc/robot/commands/AimWithLimelight.java
> +   * @param mountHeight The height of the limelight off the floor.
Clarify that this is the distance to the center of the lens

2024-02-03 18:11 UTC, willitcode commented on src/main/java/frc/robot/subsystems/Limelight.java
> +  /* This class may need logic to switch between pipelines based off of AprilTag pipeline restrictions. As
Remove the comments

2024-02-03 18:11 UTC, willitcode commented on src/main/java/frc/robot/subsystems/Limelight.java
> +   * Creates a new Limelight. Should be run once from {@link frc.robot.RobotContainer}.
Delete "Should be run once..."

2024-02-03 18:11 UTC, willitcode commented on src/main/java/frc/robot/subsystems/Limelight.java
> +   * Returns the current limelight pipeline.
Limelight pipeline number

Also you need to go through and capitalize Limelight in all JavaDoc

2024-02-03 18:48 UTC, willitcode requested changes

2024-02-03 18:48 UTC, willitcode commented on src/main/java/frc/robot/RobotContainer.java
> +  public static Limelight limelight = new Limelight("limelight");
Make this name a constant in the AimingLimelight subclass

2024-02-03 18:48 UTC, willitcode commented on src/main/java/frc/robot/commands/AimWithLimelight.java
> +   * @param distanceFromTarget How far from in inches we want to be from the target when we
delete "when we dispense"—remember this class is abstracted

2024-02-03 18:48 UTC, willitcode commented on src/main/java/frc/robot/commands/AimWithLimelight.java
> +   * @param mountHeight The height of the center of the Limelight lense off the floor.
"lens"

2024-02-03 18:48 UTC, willitcode commented on src/main/java/frc/robot/commands/AimWithLimelight.java
> +   *     Positive means backwards.
"Positive means rotated such that the lens is facing up, and not down"

2024-02-03 18:57 UTC, willitcode requested changes

2024-02-03 18:57 UTC, willitcode commented on src/main/java/frc/robot/RobotContainer.java
> +  public static Limelight limelight = new Limelight("limelight");
No seriously. Make the name of the Limelight a constant

2024-02-03 18:57 UTC, willitcode commented on src/main/java/frc/robot/commands/AimWithLimelight.java
> +   * @param speedLimit Basic speed limit to make sure we don't drive too fast. Percentage of max
Clarify this is also between 0 and 1 so people don't pass it 70 and get confused why it's not working

2024-02-05 21:55 UTC, Berdenson requested changes
Formatting and Grammar (:

2024-02-05 21:55 UTC, Berdenson commented on src/main/java/frc/robot/Constants.java
> +    public static class AimingLimelight {
Do we need an additional block for aiming the limelight? If so, I would advise moving LIMELIGHT_NAME down a block. If not, I'd remove it.

2024-02-05 21:55 UTC, Berdenson commented on src/main/java/frc/robot/subsystems/Limelight.java
> +  /* variable chaingun, I promise we use all of these */
Capitalization plz, maybe a period if you're feeling special. /lh

2024-02-05 21:55 UTC, Berdenson commented on src/main/java/frc/robot/subsystems/Limelight.java
> +  /* now its time for getter method chaingun, which I have to write manually because VS Code */
Capitalization. Also maybe remove the "write manually" "python script" parts if you want; keep if you value useless comedy.

2024-02-05 21:55 UTC, Berdenson commented on src/main/java/frc/robot/subsystems/Limelight.java
> +   * @return the current Limelight pipeline number.
Capitalize.

2024-02-05 21:55 UTC, Berdenson commented on src/main/java/frc/robot/subsystems/Limelight.java
> +   * @param name The hostname of the Limelight
de-capatalize.

2024-02-05 22:02 UTC, willitcode requested changes

2024-02-05 22:19 UTC, willitcode submitted a review, later dismissed

2024-02-05 22:26 UTC, willitcode approved these changes

2024-02-05 22:26 UTC, merged