Limit switch workaround
frc937/robot2024 pull request #50
Opened 2024-02-10 18:13 UTC by Jack-Haefele

closes #48

2024-02-10 18:26 UTC, Berdenson requested changes
Redo javadoc on copied files

2024-02-10 18:26 UTC, Berdenson commented on src/main/java/frc/robot/RobotContainer.java
>      driverController.a().onTrue(runIntake);
remove the runIntake button mapping. We don't want A to run 2 very similar commands at the same time.

2024-02-10 18:26 UTC, Berdenson commented on src/main/java/frc/robot/RobotContainer.java
>    }
We also need an additional button mapping that runs deployMailbox.

2024-02-10 18:26 UTC, Berdenson commented on src/main/java/frc/robot/commands/mailbox/DeindexNoteNoLimitSwitch.java
> +    /* If the mailbox is fully raised, run the intake. */
Remove unused comments

2024-02-10 18:26 UTC, Berdenson commented on src/main/java/frc/robot/commands/mailbox/DeindexNoteNoLimitSwitch.java
> +  private Mailbox mailbox;
Remove mailbox as we don't use it in this class

2024-02-10 18:34 UTC, QuackitsQuinn reviewed
It looks fine to me

2024-02-10 18:39 UTC, Berdenson requested changes

2024-02-10 18:39 UTC, Berdenson commented on src/main/java/frc/robot/commands/RunIntakeNoLimitSwitch.java
> +/** Command that runs the intake on the robot. */
Redo Javadoc for all copied classes.

2024-02-10 18:41 UTC, willitcode requested changes

2024-02-10 18:41 UTC, willitcode commented on src/main/java/frc/robot/commands/RunIntakeNoLimitSwitch.java
Don't make a new command for this. The intake code shouldn't need to be changed at all. Think about it: the only thing not having a limit switch on the intake will affect is that the command won't automatically end—so the driver will need to let go of the button quickly.

2024-02-10 18:41 UTC, willitcode commented on src/main/java/frc/robot/commands/mailbox/DeindexNoteNoLimitSwitch.java
Delete this whole file. Instead, replace DeindexNoteNoLimitSwitch in FireNoteRoutineNoLimitSwitch with a simple RunIntake command—they'll do the same thing in this context.

2024-02-10 18:41 UTC, willitcode commented on src/main/java/frc/robot/commands/mailbox/FireNoteRoutineNoLimitSwitch.java
> +    addCommands(new DeployMailbox(), new DeindexNoteNoLimitSwitch());
Just use a RunIntake for the second command.

2024-02-10 18:56 UTC, willitcode requested changes

2024-02-10 18:56 UTC, willitcode commented on src/main/java/frc/robot/RobotContainer.java
Bind the FireNoteRoutineNoteRoutineNoLimitSwitch command to a button

2024-02-10 18:56 UTC, willitcode commented on src/main/java/frc/robot/RobotContainer.java
Leave the regular FireNoteRoutine button alone tho—we want buttons for both

2024-02-12 21:48 UTC, Berdenson approved these changes
cheez

2024-02-12 21:52 UTC, willitcode approved these changes

2024-02-12 21:52 UTC, merged