Add Climber
frc937/robot2024 pull request #82
Opened 2024-02-24 16:17 UTC by MarissaKoglesby

closes #78

2024-02-24 16:31 UTC, willitcode requested changes

2024-02-24 16:31 UTC, willitcode commented on src/main/java/frc/robot/commands/ClimbRobotDown.java
Rename to ClimbDown. We know this is a robot.

2024-02-24 16:31 UTC, willitcode commented on src/main/java/frc/robot/commands/ClimbRobotUp.java
Rename to ClimbDown. We know this is a robot.

2024-02-24 16:31 UTC, willitcode commented on src/main/java/frc/robot/subsystems/Climber.java
> +    this.climberMotor = new CANSparkMax(Constants.Climber.CLIMBER_MOTOR_ID, MotorType.kBrushed);
Set the motor inversion state based off of a constant

2024-02-24 16:31 UTC, willitcode commented on src/main/java/frc/robot/RobotContainer.java
Instantiate commands and bind them to buttons... not dpad though, since we use that for angle snaps

2024-02-24 16:31 UTC, willitcode commented on src/main/java/frc/robot/RobotContainer.java
> +  /** Singleton instance of {@link CLimber} for the whole robot. */
De-capitalize that L, otherwise JavaDoc ain't gonna build.

2024-02-26 21:39 UTC, willitcode approved these changes

2024-02-26 21:44 UTC, Berdenson requested changes
looks good otherwise to me

2024-02-26 21:44 UTC, Berdenson commented on src/main/java/frc/robot/commands/ClimbDown.java
> +  /** Creates a new ClimbRobotUp. */
We're not creating a climb robot up here

2024-02-26 21:52 UTC, merged