Reverse intake
frc937/robot2024 pull request #94
Opened 2024-03-01 01:17 UTC by Jack-Haefele

closes #92

2024-03-01 01:19 UTC, willitcode commented
Add a description of what you did to your PR description please.

2024-03-01 01:31 UTC, willitcode requested changes

2024-03-01 01:31 UTC, willitcode commented on src/main/java/frc/robot/commands/ReverseIntake.java
Rename to RunIntakeReverse to comply with formatting. (See: commands must always start with an action verb)

2024-03-01 01:31 UTC, willitcode commented on src/main/java/frc/robot/RobotContainer.java
> +  private ReverseIntake reverseIntake = new ReverseIntake();
Remember to rename the variable when you rename the class.

2024-03-01 01:31 UTC, willitcode commented on src/main/java/frc/robot/subsystems/Intake.java
> +  public void reverseIntake() {
Also rename this to runIntakeReverse

2024-03-05 23:04 UTC, Berdenson reviewed
Looks good to me. Only issue I can see is possibly lessening the speed/power of the reverse intake. I don't know if we want it at full blast. (Don't apply anything I say until Quinn or Gabe say smth about it).

2024-03-06 20:05 UTC, willitcode approved these changes
Looks good to me. I'm not worried about making the power different unless we discover in testing that we have to.

2024-03-07 03:33 UTC, willitcode commented
@QuackitsQuinn @Jack-Haefele Gotta run spotless, then I can push the big green button

2024-03-07 03:50 UTC, willitcode requested changes

2024-03-07 03:50 UTC, willitcode commented on src/main/java/frc/robot/ekwgfnwekjgnwek
uhhhh maybe delet this? or at least don't include it in this PR?

2024-03-07 16:33 UTC, willitcode approved these changes

2024-03-07 16:46 UTC, merged